/*
 * Copyright 2018-2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

void BOARD_InitPins(void)
{
    CLOCK_EnableClock(kCLOCK_Iomuxc);
    CLOCK_EnableClock(kCLOCK_Gpio1);
    CLOCK_EnableClock(kCLOCK_Gpio2);
    CLOCK_EnableClock(kCLOCK_Gpio3);

    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U);

    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_LPUART2_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_LPUART2_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_LPUART8_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_LPUART8_RX, 0U);

    IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_41_GPIO3_IO27, 0U);

    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_00_GPIO1_IO00, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_01_GPIO1_IO01, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 0U);

    IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_FLEXPWM1_PWMA00, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_FLEXPWM1_PWMA01, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_04_FLEXPWM1_PWMA02, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_00_FLEXPWM1_PWMA03, 0U);

    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0U);

    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_00_QTIMER1_TIMER0, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_01_QTIMER1_TIMER1, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_03_QTIMER2_TIMER0, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_04_QTIMER2_TIMER1, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_00_QTIMER3_TIMER0, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_01_QTIMER3_TIMER1, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_09_QTIMER4_TIMER0, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_10_QTIMER4_TIMER1, 0U);

    IOMUXC_GPR->GPR28 &= ~(1UL << 27U);
    IOMUXC_GPR->GPR6 = ((IOMUXC_GPR->GPR6 &
                         (~(IOMUXC_GPR_GPR6_QTIMER1_TRM0_INPUT_SEL_MASK |
                            IOMUXC_GPR_GPR6_QTIMER1_TRM1_INPUT_SEL_MASK |
                            IOMUXC_GPR_GPR6_QTIMER2_TRM0_INPUT_SEL_MASK |
                            IOMUXC_GPR_GPR6_QTIMER2_TRM1_INPUT_SEL_MASK |
                            IOMUXC_GPR_GPR6_QTIMER3_TRM0_INPUT_SEL_MASK |
                            IOMUXC_GPR_GPR6_QTIMER3_TRM1_INPUT_SEL_MASK |
                            IOMUXC_GPR_GPR6_QTIMER4_TRM0_INPUT_SEL_MASK |
                            IOMUXC_GPR_GPR6_QTIMER4_TRM1_INPUT_SEL_MASK))) |
                        IOMUXC_GPR_GPR6_QTIMER1_TRM0_INPUT_SEL(0x00U) |
                        IOMUXC_GPR_GPR6_QTIMER1_TRM1_INPUT_SEL(0x00U) |
                        IOMUXC_GPR_GPR6_QTIMER2_TRM0_INPUT_SEL(0x00U) |
                        IOMUXC_GPR_GPR6_QTIMER2_TRM1_INPUT_SEL(0x00U) |
                        IOMUXC_GPR_GPR6_QTIMER3_TRM0_INPUT_SEL(0x00U) |
                        IOMUXC_GPR_GPR6_QTIMER3_TRM1_INPUT_SEL(0x00U) |
                        IOMUXC_GPR_GPR6_QTIMER4_TRM0_INPUT_SEL(0x00U) |
                        IOMUXC_GPR_GPR6_QTIMER4_TRM1_INPUT_SEL(0x00U));

    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_02_LPUART2_TX, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_03_LPUART2_RX, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_10_LPUART8_TX, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_11_LPUART8_RX, 0x10B0U);

    IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_41_GPIO3_IO27, 0x10B0U);

    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_00_GPIO1_IO00, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_01_GPIO1_IO01, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 0x10B0U);

    IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_00_FLEXPWM1_PWMA00, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_02_FLEXPWM1_PWMA01, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_04_FLEXPWM1_PWMA02, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_00_FLEXPWM1_PWMA03, 0x10B0U);

    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0xF8B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0xF8B0U);

    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_00_QTIMER1_TIMER0, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_01_QTIMER1_TIMER1, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_03_QTIMER2_TIMER0, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_04_QTIMER2_TIMER1, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_00_QTIMER3_TIMER0, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_01_QTIMER3_TIMER1, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_09_QTIMER4_TIMER0, 0x10B0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_10_QTIMER4_TIMER1, 0x10B0U);
}
